server:
  port: 8201
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coudstudy
    username: root
    password: 123456
  application:
    name: borrow-service
  cloud:
    nacos:
      discovery:
        ephemeral: false