server:
  port: 8201
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coudstudy
    username: root
    password: 123456
  data:
    redis:
      host: localhost
  application:
    name: borrow-service
  cloud:
    nacos:
      discovery:
        ephemeral: false
        cluster-name: California
        server-addr: localhost:9002
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
      block-page: /blocked
feign:
  sentinel:
    enabled: true
