server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coudstudy
    username: root
    password: 123456
  application:
    name: book-service
  data:
    redis:
      host: localhost
  cloud:
    nacos:
      discovery:
        ephemeral: false
        #namespace: c57996c1-5604-41de-94be-78b3818dec9d
        server-addr: localhost:9002
    sentinel:
      transport:
        dashboard: localhost:8858